name: Build & Publish

on:
  pull_request:
    paths:
      - ".github/workflows/build-and-publish.yml"
      - "setup.*"

  workflow_dispatch:
    inputs:
      branch:
        description: "The branch, tag or SHA to release from"
        required: true
        default: "master"

jobs:
  os-built-distributions:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
          submodules: true
      
      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all
          
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install build dependencies
        run: python -m pip install --upgrade cibuildwheel
      - name: Build wheels
        run: python -m cibuildwheel
        env:
          CIBW_SKIP: "cp36-*" # skip 3.6
          CIBW_ARCHS_LINUX: aarch64
      - uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions-linux
          path: ./wheelhouse/*.whl

