name: Tests

on:
  pull_request:
    paths:
      - ".github/workflows/tests.yml"
      - "marisa-trie/**/*.cc"
      - "marisa-trie/**/*.h"
      - "setup.py"
      - "tests/*.py"

jobs:
  tests:
    name: Run tests for ${{ matrix.os }} for ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: [3.6, 3.7, 3.8, 3.9, "3.10.0-beta.4"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
          submodules: true
      - name: Use Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install test dependencies
        run: python -m pip install ".[test]"
      - name: Test
        run: python -m pytest
